// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BoundingBox: typeof import('C:/Users/Administrator/Documents/Projects/Personal/poc-boxes-component/src/components/BoundingBox.vue')['default']
    DrawingBox: typeof import('C:/Users/Administrator/Documents/Projects/Personal/poc-boxes-component/src/components/DrawingBox.vue')['default']
    HelloWorld: typeof import('C:/Users/Administrator/Documents/Projects/Personal/vite-vue3-boilerplate/src/components/HelloWorld.vue')['default']
    MainBoard: typeof import('C:/Users/Administrator/Documents/Projects/Personal/poc-boxes-component/src/components/MainBoard.vue')['default']
  }
}

export { }
